DojoSecrets/config/routes.rb
Rails.application.routes.draw do

  get 'likes/destroy'

  get 'secrets/index'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :secrets, only: [:index, :create, :destroy]
  resources :likes, only: [:create, :destroy]

end

DojoSecrets/app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :secret
end

DojoSecrets/app/models/secret.rb
class Secret < ActiveRecord::Base
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  validates :content, presence: true
end

DojoSecrets/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :secrets
  has_many :likes, dependent: :destroy
  has_many :secrets, through: :likes, source: :secret

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }
  
  before_save :email_lowercase

  def email_lowercase
    email.downcase!
  end
end

DojoSecrets/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :require_login
  
  def require_login
    redirect_to new_session_path unless session[:user_id]
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user
end

DojoSecrets/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    puts "entrei no create do likes" 
    Like.create like_params
    redirect_to "/secrets"
  end

  def destroy
    @like = Like.find(params[:id])
    @like.destroy if current_user === @like.user
    redirect_to "/secrets"    
  end

  private
    def like_params
      params.require(:like).permit(:secret_id).merge(user: current_user)
    end
end

DojoSecrets/app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def index
    @secrets = Secret.all
  end

  def create
    secret = Secret.new secret_params
    unless secret.save
      flash[:errors] = secret.errors.full_messages
    end
    redirect_to "/users/#{current_user.id}"
  end

  def destroy
    @secret = Secret.find(params[:id])
    @secret.destroy if @secret.user === current_user
    redirect_to "/users/#{current_user.id}"
  end

  private
    def secret_params
      params.require(:secret).permit(:content).merge(user: current_user)
    end
end

DojoSecrets/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

    def new
        # render login page
    end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to "/users/#{@user.id}"
    else 
      flash[:errors] = ["Invalid Authentication"]
      redirect_to new_session_path
    end
  end

    def destroy
        # Log User out
        session[:user_id] = nil
        redirect_to new_session_path
    end

end

DojoSecrets/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :require_correct_user, only: [:edit, :show, :update, :destroy]

  def new
   @user = User.new
  end

  def show
  	@user = User.find(params[:id])
    @secrets = Secret.where(user_id: params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to "/sessions/new"
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to "/users/new"
    end
  end
  
  def update
    @user = User.find(params[:id])
    @user.name = params[:name]
    @user.email = params[:email]
    if @user.save
      redirect_to "/users/#{@user.id}", notice: "You have successfully updated a User!"
    else
      flash[:errors] = @user.errors.full_messages     
      redirect_to "/users/#{@user.id}/edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      reset_session
      redirect_to "/users/new"
    else
      redirect_to "/users/#{@user.id}/edit"
    end
  end  


  private

  def require_correct_user
    if current_user != User.find(params[:id])
      redirect_to "/users/#{session[:user_id]}"
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

DojoSecrets/app/helpers/application_helper.rb
module ApplicationHelper
end

DojoSecrets/app/helpers/likes_helper.rb
module LikesHelper
end

DojoSecrets/app/helpers/secrets_helper.rb
module SecretsHelper
end

DojoSecrets/app/helpers/sessions_helper.rb
module SessionsHelper
end

DojoSecrets/app/helpers/users_helper.rb
module UsersHelper
end

DojoSecrets/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DojoSecrets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:errors] %>
  <% flash[:errors].each do |e| %>
    <%= e %>
  <% end %>
<% end %>

<% if current_user %>
  <form action="/sessions/<%=current_user.id%>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="delete">
    <input type="submit" class="btn btn-default" value="Log Out">
  </form>
<% end %> 

<%= yield %>

</body>
</html>

DojoSecrets/app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

DojoSecrets/app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

DojoSecrets/app/views/secrets/index.html.erb
<h1>All Secrets</h1>
<% @secrets.all.each do |secret| %>
	<h1><%= secret.content %></h1>
	<h3><%= secret.likes.count %> likes</h3>
	<% if secret.user == current_user %>
		<form action = "/secrets/<%= secret.id %>" method = "post">
		    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<input type="hidden" name="_method" value="delete">
			<input type = 'submit' value = "Delete Secret">
		</form>
	<% end %>
	<% unless secret.users.include?(current_user) %>
		<form action = "/likes" method = "post">
		    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		    <input type="hidden" name="like[secret_id]" value = "<%= secret.id %>">
			<input type="submit" name="Like" value = "Like">			
		</form>	
	<% else %>
		<form action = "/likes/<%= Like.where(user: current_user, secret: secret).first.id%>" method = "post">
		    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<input type="hidden" name="_method" value="delete">
			<input type="submit" name="Unlike" value = "Unlike">
		</form>
	<% end %>	
<% end %>

DojoSecrets/app/views/users/edit.html.erb
<div class="panel-heading">

    <h3>Editing <%= @user.name %></h3>	

	<form action="/users/<%= @user.id %>" method='post'>
		<input type="hidden" name="_method" value="patch">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		<p>
			<label>Name:</label>
			<input type="text" name="name" value="<%= @user.name %>">
		</p>
        <p>
        	<label>Email:</label>
			<input type="text" name="email" value="<%= @user.email %>">
		</p>
		<button type="submit" class="btn btn-default">Update User</button>		
	</form>

	<form action="/users/<%= @user.id %>" method='post'>
		<input type="hidden" name="_method" value="delete">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		<button type="submit" class="btn btn-default">Delete User</button>		
	</form>



	<%= link_to "Home", new_user_path %>

</div>

DojoSecrets/app/views/users/new.html.erb
<div class="col-lg-12">  

    <h3>Creating a New User</h3>

	<div class="panel-heading"> 
	<%= form_for(@user) do |u| %>

	<div class="form-group">
		<%= u.label :name %>
		<%= u.text_field :name %>
	
		<%= u.label :email%>
		<%= u.email_field :email %>

		<%= u.label :password %>
		<%= u.password_field :password %>

		<%= u.label :password %>
		<%= u.password_field :password_confirmation %>
		<button type="submit" class="btn btn-default">Create</button>
	</div>

	<% end %>
	<%= link_to "Home", sessions_path %>
</div>

DojoSecrets/app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<%= link_to "Edit Profile", edit_user_path(@user) %>

<form action = "/secrets" method = "post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<input type="text" id="Content" name = "secret[content]">
	<input type="submit" value = "Create Secret">
</form>
</br>

<h1>Secrets</h1>
<% @secrets.each do |secret| %>
	<h1><%= secret.content %></h1>
	<h3><%= secret.likes.count %> likes</h3>	
	<% if secret.user == current_user %>
		<form action = "/secrets/<%= secret.id %>" method = "post">
		    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<input type="hidden" name="_method" value="delete">
			<input type = 'submit' value = 'Delete Secret'>
		</form>
	<% end %>
<% end %>